name: todo_plugin
description: "Probation Project at VietinBank."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  plugin_platform_interface: ^2.0.2
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.vtb.todo_plugin
        pluginClass: TodoPlugin
      ios:
        pluginClass: TodoPlugin

  assets:
    - assets/
    - assets/icons/

  # fonts:
    #  - family: Schyler
    #    fonts:
    #      - asset: fonts/Schyler-Regular.ttf
    #      - asset: fonts/Schyler-Italic.ttf
    #        style: italic
    #  - family: Trajan Pro
    #    fonts:
    #      - asset: fonts/TrajanPro.ttf
    #      - asset: fonts/TrajanPro_Bold.ttf
    #        weight: 700
